AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sdl-slack-send-block-ip
Parameters:
  NetworkAclId:
    Type: String
    Description: Network ACL ID
  SlackWebhookUrl:
    Type: String
    Description: Webhook for sending messages to slack
  TaskQueueName:
    Type: String
    Description: SQS Queue Name for Tasks
  TaskQueueUrl:
    Type: String
    Description: SQS Queue Url for Tasks

Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Tracing: Active
  Api:
    TracingEnabled: true
Resources:
  SdlFilterBruteForceAttacks:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: filter-brute-force-attacks/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
        - arm64

  SdlCheckNaclForIP:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: nacl-check-if-blocked/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
        - arm64
      Policies:
        - AmazonEC2ReadOnlyAccess
      Environment:
        Variables:
          nacl_id: !Ref NetworkAclId

  SdlSlackSendBlockIP:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: slack-send-block-ip/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
        - arm64
      Environment:
        Variables:
          slack_url: !Ref SlackWebhookUrl

  SdlSlackCallbackWebhook:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: slack-callback-webhook/
      Handler: app.lambda_handler
      Runtime: python3.11
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            Path: /
            Method: POST
      Architectures:
        - arm64
      Policies:
        - SQSSendMessagePolicy:
            QueueName:
              !Ref TaskQueueName
      Environment:
        Variables:
          sqs_url: !Ref TaskQueueUrl

  SdlNaclBlockIP:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: nacl-block-ip/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
        - arm64
      Policies:
        - AmazonEC2FullAccess
        - AWSStepFunctionsFullAccess
        - SQSPollerPolicy:
            QueueName:
              !Ref TaskQueueName
      Environment:
        Variables:
          nacl_id: !Ref NetworkAclId
          slack_url: !Ref SlackWebhookUrl

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
Outputs:
  SdlFilterBruteForceAttacksFunction:
    Description: SDL Filter Brute Force Attacks Lambda Function ARN
    Value: !GetAtt SdlFilterBruteForceAttacks.Arn
  SdlCheckNaclForIPFunction:
    Description: SDL Check Nacl For IP Lambda Function ARN
    Value: !GetAtt SdlCheckNaclForIP.Arn
  SdlSlackSendBlockIPFunction:
    Description: SDL Slack Send Block IP Lambda Function ARN
    Value: !GetAtt SdlSlackSendBlockIP.Arn
  SdlSlackCallbackWebhookFunction:
    Description: SDL Slack Callback Webhook Lambda Function ARN
    Value: !GetAtt SdlSlackCallbackWebhook.Arn
  SdlNaclBlockIPFunction:
    Description: SDL SQS read and block function Lambda Function ARN
    Value: !GetAtt SdlSlackCallbackWebhook.Arn
  SdlSlackSendBlockIPIamRole:
    Description: Implicit IAM Role created for SDL Slack Send Block IP Lambda Function
    Value: !GetAtt SdlSlackSendBlockIP.Arn
